### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jaredfreedman** [jaredfreedman/edna_metabarcoding#1]
This is for comments and suggestions on my project proposal for Analytical Workflows

**Comment by dymite** [comment]
Thank you for your presentation, Jared! I admire the detail in which you were able to describe your metabarcoding analysis. I also thought it was clever to present possible solutions alongside your anticipated challenges (:

**Comment by varyl97** [comment]
Really interesting project Jared! I really like the note about creating a modular/adaptable workflow - this is similar to what I'm trying to do as well with my workflow so I'm excited to see how you proceed.

**Comment by Medelinkant** [comment]
Jared, 
Great presentation! I liked how you organized your proposed project workflow. I think it's useful to outline possible solutions to your anticipated challenges from the beginning-- demonstrates your ability to plan through a project.

**Comment by JustinHockett** [comment]
I like that you put potential solutions to your challenges and it seems like you have a relatively thought out process to follow once you get data in hand

**Comment by sielerjm** [comment]
For keeping track of sample/file names that are similar, one thing I've found helpful is to utilize `for loops` to rename samples names to something akin to `PojectName_SampleName` and for OTUs you could name them `ProjectNameYear_OTU000#`. I have a couple of code chunks I could share after class that help with that.

**Comment by ssidder** [comment]
I thought you did a great job explaining your project goals for scripting and how the process will look (I believe slide 3). Even though I am unfamiliar with your area of expertise, but was able to follow your plan for workflow easily. 

A suggestion would be to define what metabarcoding means early in the presentation. You might have mentioned this, but I was left wondering what that process means in non-technical terms. 

Suggestion for naming conventions: I'd suggest writing out a protocol for how you plan to name things and creating an example so that when you go to naming your files you aren't tempted to do it on the fly but rather you already have a process for outlining how files should be name. That approach has helped me in the past!

**Comment by maddie-hicks** [comment]
eDNA is a super cool tool and your project sounds really interesting!  I'm considering using eDNA as well for my project to track use of seasonal habitats by Chinook salmon but I don't know much about the process of analyzing eDNA data so it was great to learn a bit more about it in your presentation.

**Comment by kjtonra** [comment]
Nice presentation- I'm excited to see how you use this workflow to analyze eDNA data. I'll have to do that later this quarter, so keep me updated! I like to use Adobe Bridge for batch naming samples. You can add different fields and name hundreds of files consistently at once, so it's especially useful for big datasets.

**Comment by cheyennejarman** [comment]
Hi Jared,

I think one way to address your concern about file naming convention could be before you start coding write up a mock methods procedure of how you think it will go - from where to access data files to getting your R code started. This will definitely change but it could be - ̗̀ Nice ̖́- to have this basic framework where you can include file naming convention.

For the concern for the lack of your own data, I would recommend looking at other eDNA papers that have output and see if you can replicate it.

I find eDNA super interesting so I am excited to see what kind of output you get!
